# Generated by Django 4.2.13 on 2024-06-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="bannner_title",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
