# Generated by Django 4.2.13 on 2024-06-16 07:39

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_homepage_banner_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="banner_subtitle",
            field=wagtail.fields.RichTextField(default="New sub"),
            preserve_default=False,
        ),
    ]
