# Generated by Django 4.2.13 on 2024-06-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_contactpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactpage",
            name="page_title",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
